# Generated by Django 4.2.9 on 2024-01-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_habits_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='what_time',
            new_name='perform_time',
        ),
        migrations.AddField(
            model_name='habits',
            name='chat_id',
            field=models.CharField(default=1, max_length=50, verbose_name='id tg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habits',
            name='date_next_reminder',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата следующего напоминания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки'),
        ),
    ]
